apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-app-ingress
  namespace: uptime-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - uptime.local
      secretName: uptime-tls
  rules:
    - host: uptime.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-app-service
                port:
                  number: 8080
