apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-app-ingress
  namespace: uptime-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: uptime.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: uptime-app-service
              port:
                number: 8080

