apiVersion: v1
kind: Service
metadata:
  name: uptime-app-service
  namespace: uptime-dev
spec:
  type: NodePort
  selector:
    app: uptime-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
