apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: uptime-dev
type: Opaque
stringData:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: uptime_db
  DB_USER: uptime_user
  DB_PASSWORD: uptime_pass
